# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :disable_input_output_paths => true

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  #三方库工具
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'Masonry'#约束库
  pod 'DZNEmptyDataSet'
  pod 'YYKit'
  pod 'ReactiveObjC'#RAC
  pod 'GKPhotoBrowser', '3.1.3' #图片浏览 视频播放
  pod 'SDCycleScrollView' #banner
  pod 'FreeStreamer'#音频播放
  pod 'FGIAPService'#苹果支付
  pod 'SocketRocket'#长链接
  pod 'SVGAPlayer'#svga动画播放
  pod 'AliyunOSSiOS', '2.10.22'#阿里云OSS
  pod 'FURenderKit-lite'#FURenderKit人脸特效版本，美颜 只需要留ai_face_processor.bundle和face_beautification.bundle
  #导航分页
  pod 'JXCategoryView' #导航分页 解决tabbar悬浮处理方案
  pod 'JXPagingView/Pager'
  #巨量SDK
  pod 'BDASignalSDK'
  pod 'Protobuf'
  #友盟依赖库
  pod 'UMCommon'
  pod 'UMDevice'
  pod 'UMShare/Social/WeChat'#包含了微信分享、登录 功能  23M
  pod 'UMLink'
  #云信基础kit库
  pod 'NECoreIMKit/NOS_Special', '9.6.7'
  pod 'NECoreKit', '9.6.6'
  pod 'NEChatKit/NOS_Special', '9.7.3'
  pod 'NIMSDK_LITE', '9.20.12'#50M
  pod 'NECommonUIKit', '9.7.1'
  pod 'NECommonKit', '9.6.6'
  pod 'NERtcCallKit/NOS_Special', '2.5.2'
  pod 'NERtcSDK', '5.8.10', :subspecs => ['RtcBasic'] #75M
  pod 'NEConversationUIKit', :path => 'Runner/NEConversationUIKit/NEConversationUIKit.podspec'  #网易云信 会话列表组件
  pod 'NEChatUIKit', :path => 'Runner/NEChatUIKit/NEChatUIKit.podspec'          #网易云信 chat组件
  #短视频模块
  pod 'UGCKit', :path => 'Runner/UGCKit/UGCKit.podspec', :subspecs => ["UGC"]
  pod 'TXLiteAVSDK_UGC'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      #升级xcode15提示报错新增
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end 
 
