name: Build and Distribute

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use local IPA (skip cloud build)
        env:
          LOCAL_IPA_DIR: ios_dist
        run: | 
          set -e
          if [ ! -d "$LOCAL_IPA_DIR" ]; then
            echo "$LOCAL_IPA_DIR not found. Create it in repo root and add your prebuilt .ipa, then push."
            exit 1
          fi
          cd "$LOCAL_IPA_DIR"
          IPA_FILE=$(ls -1 *.ipa 2>/dev/null | head -n 1 || true)
          if [ -z "$IPA_FILE" ]; then
            if compgen -G "splitfile_*" > /dev/null; then
              echo "No single .ipa found, but detected split parts. Merging splitfile_* -> Runner_merged.ipa ..."
              cat splitfile_* > Runner_merged.ipa
              IPA_FILE=Runner_merged.ipa
              echo "Merged IPA size:" && ls -lah "$IPA_FILE"
            else
              echo "No .ipa and no splitfile_* in $LOCAL_IPA_DIR. Place your prebuilt .ipa or split parts here and push again."
          ls -la
          exit 1
            fi
          fi
          # 依据 Info.plist 生成规范文件名：{AppName}-{version}-{build}.ipa（ASCII、无空格）
          TMPDIR_RENAME="$(mktemp -d)"
          unzip -q "$IPA_FILE" -d "$TMPDIR_RENAME"
          APP_PATH_RENAME=$(find "$TMPDIR_RENAME/Payload" -maxdepth 1 -name "*.app" | head -n 1)
          if [ -d "$APP_PATH_RENAME" ]; then
            BUNDLE_ID=$(/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' "$APP_PATH_RENAME/Info.plist" 2>/dev/null || true)
            SHORT_VER=$(/usr/libexec/PlistBuddy -c 'Print CFBundleShortVersionString' "$APP_PATH_RENAME/Info.plist" 2>/dev/null || true)
            BUILD_VER=$(/usr/libexec/PlistBuddy -c 'Print CFBundleVersion' "$APP_PATH_RENAME/Info.plist" 2>/dev/null || true)
            # App 名称优先使用 CFBundleDisplayName 其次 CFBundleName，否则取 bundleId 尾段
            APP_NAME=$(/usr/libexec/PlistBuddy -c 'Print CFBundleDisplayName' "$APP_PATH_RENAME/Info.plist" 2>/dev/null || true)
            if [ -z "$APP_NAME" ]; then
              APP_NAME=$(/usr/libexec/PlistBuddy -c 'Print CFBundleName' "$APP_PATH_RENAME/Info.plist" 2>/dev/null || true)
            fi
            if [ -z "$APP_NAME" ]; then
              APP_NAME=${BUNDLE_ID##*.}
            fi
            # 仅保留 ASCII 安全字符，统一用短横线
            SAFE_APP=${APP_NAME//[^A-Za-z0-9_.-]/-}
            if [ -z "$SAFE_APP" ]; then
              SAFE_APP="App"
            fi
            SAFE_SHORT=${SHORT_VER//[^A-Za-z0-9_.-]/-}
            SAFE_BUILD=${BUILD_VER//[^A-Za-z0-9_.-]/-}
            NEW_IPA_NAME="$SAFE_APP-$SAFE_SHORT-$SAFE_BUILD.ipa"
            # 避免文件名以 '-' 开头导致命令误判为选项
            case "$NEW_IPA_NAME" in
              -*) NEW_IPA_NAME="App${NEW_IPA_NAME}" ;;
            esac
            mv "$IPA_FILE" "$NEW_IPA_NAME" || cp "$IPA_FILE" "$NEW_IPA_NAME"
            IPA_FILE="$NEW_IPA_NAME"
          fi
          rm -rf "$TMPDIR_RENAME"
          echo "Using IPA file: $IPA_FILE"
          echo "IPA_FILE_NAME=$IPA_FILE" >> $GITHUB_ENV
          echo "IPA_DIR=$(pwd)" >> $GITHUB_ENV
          echo "IPA_FULL_PATH=$(pwd)/$IPA_FILE" >> $GITHUB_ENV

      - name: Setup iTMSTransporter (diagnostics)
        run: |
          set -e
          cd "$IPA_DIR"
          if [ ! -d "itsm" ]; then
            git clone https://github.com/ZhangLi1984/itsm.git
          else
            cd itsm && git pull && cd ..
          fi
          chmod +x ./itsm/bin/iTMSTransporter

      - name: "Diagnostics: List providers"
        env:
          APPLE_USERNAME: chixin@lurcohongkong.shop
          APPLE_PASSWORD: debx-pouz-pslg-jruf
        run: |
          set -e
          cd "$IPA_DIR"
          echo "Listing available providers for $APPLE_USERNAME ..."
          ./itsm/bin/iTMSTransporter -m provider -u "$APPLE_USERNAME" -p "$APPLE_PASSWORD" || true

      - name: "Diagnostics: IPA metadata & provisioning"
        run: |
          set -e
          cd "$IPA_DIR"
          echo "IPA checksum and size:"
          shasum -a 256 "$IPA_FILE_NAME" || true
          md5 "$IPA_FILE_NAME" 2>/dev/null || true
          echo "Extracting Info.plist ..."
          TMPDIR="$(mktemp -d)"
          unzip -q "$IPA_FILE_NAME" -d "$TMPDIR"
          APP_PATH=$(find "$TMPDIR/Payload" -maxdepth 1 -name "*.app" | head -n 1)
          if [ -d "$APP_PATH" ]; then
            echo "BundleIdentifier: $(/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' "$APP_PATH/Info.plist" 2>/dev/null || true)"
            echo "ShortVersion: $(/usr/libexec/PlistBuddy -c 'Print CFBundleShortVersionString' "$APP_PATH/Info.plist" 2>/dev/null || true)"
            echo "BuildVersion: $(/usr/libexec/PlistBuddy -c 'Print CFBundleVersion' "$APP_PATH/Info.plist" 2>/dev/null || true)"
            if [ -f "$APP_PATH/embedded.mobileprovision" ]; then
              echo "embedded.mobileprovision summary (TeamIdentifier / Entitlements / ProvisionsAllDevices / get-task-allow):"
              security cms -D -i "$APP_PATH/embedded.mobileprovision" 2>/dev/null | plutil -p - 2>/dev/null | \
                egrep "TeamIdentifier|application-identifier|aps-environment|get-task-allow|ProvisionsAllDevices" || true
            else
              echo "No embedded.mobileprovision found in app"
            fi
          else
            echo "Could not locate .app in IPA"
          fi
          rm -rf "$TMPDIR"

      - name: "Diagnostics: Verify IPA with iTMSTransporter"
        env:
          APPLE_USERNAME: chixin@lurcohongkong.shop
          APPLE_PASSWORD: debx-pouz-pslg-jruf
        run: |
          set -e
          cd "$IPA_DIR"
          ./itsm/bin/iTMSTransporter -m verify -assetFile "$IPA_FILE_NAME" -u "$APPLE_USERNAME" -p "$APPLE_PASSWORD" || true

      - name: Archive IPA
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa-${{ github.run_number }}
          path: ${{ env.IPA_FULL_PATH }}
      
      - name: Upload using iTMSTransporter
        env:
          APPLE_USERNAME: chixin@lurcohongkong.shop
          APPLE_PASSWORD: debx-pouz-pslg-jruf
          APPLE_ASC_PROVIDER: 79L3K25T7P
        run: |
          set -e
          cd "$IPA_DIR"
          if [ ! -d "itsm" ]; then
            git clone https://github.com/ZhangLi1984/itsm.git
          else
            cd itsm && git pull && cd ..
          fi
          chmod +x ./itsm/bin/iTMSTransporter
          set +e
          echo "Trying upload without provider ..."
          ./itsm/bin/iTMSTransporter -m upload -assetFile "$IPA_FILE_NAME" -u "$APPLE_USERNAME" -p "$APPLE_PASSWORD"
          STATUS=$?
          if [ $STATUS -ne 0 ]; then
            echo "Retrying upload with -itc_provider ..."
            ./itsm/bin/iTMSTransporter -m upload -assetFile "$IPA_FILE_NAME" -u "$APPLE_USERNAME" -p "$APPLE_PASSWORD" -itc_provider "$APPLE_ASC_PROVIDER"
            STATUS=$?
          fi
          if [ $STATUS -ne 0 ]; then
            echo "Retrying upload with -asc_provider ..."
            ./itsm/bin/iTMSTransporter -m upload -assetFile "$IPA_FILE_NAME" -u "$APPLE_USERNAME" -p "$APPLE_PASSWORD" -asc_provider "$APPLE_ASC_PROVIDER"
            STATUS=$?
          fi
          if [ $STATUS -ne 0 ]; then
            echo "Upload failed with both provider flags. Running verify for diagnostics..."
            ./itsm/bin/iTMSTransporter -m verify -f "$IPA_FILE_NAME" -u "$APPLE_USERNAME" -p "$APPLE_PASSWORD" || true
            exit $STATUS
          fi

      - name: Check Upload Status
        if: ${{ failure() }}
        run: |
          echo "❌ Upload failed! Common fixes:"
          echo " 运行验证命令: /usr/local/itms/bin/iTMSTransporter -m verify -assetFile build/${{ env.IPA_FILE }}"